services:
  backend:
    image: backend:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8888:8888"
    command: npx nodemon server.js
    